version: '3.1'
services:
    webserver:
        image: nginx
        working_dir: /var/www/project
        volumes:
            - './:/var/www/project'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        working_dir: /var/www/project
        volumes:
            - './:/var/www/project'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        depends_on:
            - db

    node:
        image: node
        working_dir: /var/www/project
        volumes:
            - './:/var/www/project'
        command: tail -F anything
        # command: [sh, -c, "npm run watch"]

    db:
        image: postgres
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        ports: 
            - '5432:5432'
        volumes: 
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
